name: Android Instrumented Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  list-avds:
    runs-on: ubuntu-latest

    steps:
      - name: Show AVD Devices
        run: |
          echo "Try avdmanager:"
          ${ANDROID_HOME}/cmdline-tools/latest/bin/avdmanager list device || echo "avdmanager not found or missing JAXB"

  instrumented-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17



      - name: Run Instrumented Tests on Emulator
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel_4
          emulator-options: -no-window -no-audio -no-snapshot
          disable-animations: true
          script: ./gradlew connectedDebugAndroidTest
