name: Android CI Instrumented Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  instrumented-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Ensure KVM permissions for current user
        run: |
          echo "Ensuring KVM permissions for user: $(whoami)"
          # Füge den aktuellen Benutzer zur kvm-Gruppe hinzu
          sudo gpasswd -a $(whoami) kvm
          # Überprüfe, ob die Gruppe dem Benutzer zugewiesen wurde
          groups $(whoami)
          # Stelle sicher, dass die KVM-Gerätedatei für die Gruppe les- und schreibbar ist
          sudo chmod 0666 /dev/kvm || true # `|| true` um Fehler zu ignorieren, falls /dev/kvm noch nicht existiert oder Berechtigungsprobleme
          echo "KVM setup attempt completed."

      - name: Run Instrumented Tests on Emulator
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          emulator-options: -no-window -no-audio -no-snapshot
          disable-animations: true
          script: ./gradlew connectedDebugAndroidTest --info
