name: Android CI Instrumented Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  instrumented-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache Android SDK
        uses: actions/cache@v3
        with:
          path: |
            ~/.android/sdk
            ~/.android/avd
          key: ${{ runner.os }}-android-sdk-${{ hashFiles('**/build.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-android-sdk-

      - name: Ensure KVM permissions for current user
        run: |
          echo "Ensuring KVM permissions for user: $(whoami)"
          sudo gpasswd -a $(whoami) kvm
          groups $(whoami)
          sudo chmod 0666 /dev/kvm || true # `|| true` um Fehler zu ignorieren, falls /dev/kvm noch nicht existiert oder Berechtigungsprobleme
          echo "KVM setup attempt completed."

      - name: Run Instrumented Tests on Emulator
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          emulator-options: -no-window -no-audio -no-snapshot
          disable-animations: true
          script: ./gradlew connectedDebugAndroidTest --info
